sonar.projectKey=vitoriaamaral09_prova2-unit-vitoriaviana
sonar.organization=vitoriaamaral09
sonar.projectName=Jest Integration Tests
sonar.projectVersion=1.0
sonar.sources=./test
sonar.sourceEncoding=UTF-8
